/*
 * Copyright (C) 2016 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.example.android.datasellertransactionstracker.data;

/**
 * Created by Qausim on 8/3/2018.
 */

import android.provider.BaseColumns;

import java.net.PortUnreachableException;
import java.net.SocketTimeoutException;

/**
 * API contract class for the transaction tracker app.*/
public final class TransactionContract {
    // To prevent anyone from accidentally instantiating the class give it an empty constructor.
    private void TrasactionContract() {}

    // Inner class implements BaseColumns, contains constant values for the transaction table name and
    // its fields
    public static final class TransactionEntry implements BaseColumns {
        // The table name. The table has fields ID, Phone, Amount, Title, Paid, Description
        // and date.
        public static final String TABLE_NAME = "transactions";

        // Field name for autogenerated _ID for each entry
        public static final String _ID = BaseColumns._ID;

        // The table's ID field a unique identifier (name, phone)
        public static final String NAME = "name";

        // Field name for the customer's or service provider's phone number
        public static final String PHONE = "phone";

        // Field name for the service provided
        public static final String UNIT = "unit";

        // Field name for the amount of transaction
        public static final String COST = "cost";

        // Field name for the individual's title, whether a customer or service provider;
        public static final String TITLE = "title";

        // Field name for pending payments and their amounts
        public static final String PAYMENT_STATE = "payment";

        // Field name for the description (extra notes about what transpired) of each transaction
        public static final String DESCRIPTION = "description";

        // Field name for the date
        public static final String DATE = "date";

        // The title field is limited options field. The individual is either a customer or a
        // service provider
        // Constant integer variables will be declared for each
        // For a customer
        public static final int CUSTOMER = 1;
        // For a service provider
        public static final int SERVICE_PROVIDER = 2;

        // For the payment state
        // If paid
        public static final int PAID = 3;
        // If pending
        public static final int PENDING = 4;
    }
}